"""remove unique from username

Revision ID: 6558843bc4ca
Revises: 7f35bcc15585
Create Date: 2020-05-10 08:04:45.086126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6558843bc4ca'
down_revision = '7f35bcc15585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###
